services:
  timetodo-apitest:
    container_name: timetodo-apitest
    image: "harriet99/timetodo-apitest:latest"
    ports:
      - "8080:8080"  # API 서비스 포트 매핑
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"

  nginx-proxy-manager:
    container_name: npm
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"     # HTTP 포트
      - "443:443"   # HTTPS 포트
      - "81:81"     # NPM 대시보드 포트
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"