CREATE TABLE `USER_PREFERENCES` (
  `IDX` bigint NOT NULL AUTO_INCREMENT COMMENT '사용자 설정 IDX',
  `DDAY_SORT_TYPE` varchar(255) COMMENT 'D-day 정렬 타입',
  `CATEGORY_SORT_TYPES` varchar(255) COMMENT '카테고리 정렬 타입',
  `NOTIFICATION_TYPES` varchar(255) COMMENT '알림 타입',
  `CREATE_DT` datetime(6) NOT NULL COMMENT '생성일시',
  `UPDATE_DT` datetime(6) NOT NULL COMMENT '수정일시',
  PRIMARY KEY (`IDX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `USERS` (
  `USERNAME` varchar(255) NOT NULL COMMENT '아이디',
  `PASSWORD` varchar(255) NOT NULL COMMENT '암호',
  `EMAIL` varchar(255) NOT NULL COMMENT '이메일',
  `NICKNAME` varchar(255) NOT NULL COMMENT '닉네임',
  `REFRESH_TOKEN` varchar(255) DEFAULT NULL COMMENT '리프레쉬 토큰',
  `ENABLED` bit(1) NOT NULL COMMENT '활성화 여부',
  `ACCOUNT_NON_EXPIRED` bit(1) NOT NULL COMMENT '계정 만료 여부',
  `ACCOUNT_NON_LOCK` bit(1) NOT NULL COMMENT '계정 잠금 여부',
  `PASS_FAIL_COUNT` int NOT NULL COMMENT '계정 틀린횟수',
  `CREATE_DT` datetime(6) NOT NULL COMMENT '생성일시',
  `UPDATE_DT` datetime(6) NOT NULL COMMENT '수정일시',
  `DELETE_DT` datetime(6) DEFAULT NULL COMMENT '삭제일시',
  `STATUS` CHAR(1) NOT NULL COMMENT '상태',
  `PREFERENCE_IDX` bigint DEFAULT NULL COMMENT '사용자 설정 IDX',
  PRIMARY KEY (`USERNAME`),
  KEY `FKl8gm1dxq348hfgh94p7er9c21` (`PREFERENCE_IDX`),
  CONSTRAINT `FKl8gm1dxq348hfgh94p7er9c21` FOREIGN KEY (`PREFERENCE_IDX`) REFERENCES `USER_PREFERENCES` (`IDX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `AUTHORITIES` (
  `USERNAME` varchar(255) NOT NULL COMMENT '유저 아이디',
  `AUTHORITY` varchar(255) NOT NULL COMMENT '권한',
  PRIMARY KEY (`AUTHORITY`,`USERNAME`),
  KEY `FKl8gm1dxqhdixkdsm1p7er9c21` (`USERNAME`),
  CONSTRAINT `FKl8gm1dxqhdixkdsm1p7er9c21` FOREIGN KEY (`USERNAME`) REFERENCES `USERS` (`USERNAME`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `TERMS` (
  `IDX` bigint NOT NULL AUTO_INCREMENT COMMENT '약관 IDX',
  `TITLE` varchar(255) NOT NULL COMMENT '약관 제목',
  `CONTENT` varchar(255) NOT NULL COMMENT '약관 내용',
  `CATEGORY` varchar(255) NOT NULL COMMENT '약관 카테고리',
  `LANG_DIV_CD` enum('ENG','KOR') NOT NULL COMMENT '약관 언어 타입 [KOR한국, ENG영어]',
  `CREATE_DT` datetime(6) NOT NULL COMMENT '생성일시',
  `UPDATE_DT` datetime(6) NOT NULL COMMENT '수정일시',
  `DELETE_DT` datetime(6) DEFAULT NULL COMMENT '삭제일시',
  `STATUS` CHAR(1) NOT NULL COMMENT '상태',
  PRIMARY KEY (`IDX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `TERMS_AGREE` (
  `IDX` bigint NOT NULL AUTO_INCREMENT COMMENT '약관 동의 IDX',
  `TERMS_IDX` bigint DEFAULT NULL COMMENT '약관 IDX',
  `USERNAME` varchar(255) DEFAULT NULL COMMENT '약관 동의자 아이디',
  `IP` varchar(255) NOT NULL COMMENT '약관 동의 한 IP주소',
  `AGREE_YN` bit(1) NOT NULL COMMENT '동의여부',
  `CREATE_DT` datetime(6) NOT NULL COMMENT '생성일시',
  `UPDATE_DT` datetime(6) NOT NULL COMMENT '수정일시',
  `DELETE_DT` datetime(6) DEFAULT NULL COMMENT '삭제일시',
  `STATUS` CHAR(1) NOT NULL COMMENT '상태',
  PRIMARY KEY (`IDX`),
  KEY `FK20od6sgi7o047ck2ra24uus8p` (`TERMS_IDX`),
  KEY `FKnr2fb9f4al3pj2jt8rd4kauih` (`USERNAME`),
  CONSTRAINT `FK20od6sgi7o047ck2ra24uus8p` FOREIGN KEY (`TERMS_IDX`) REFERENCES `TERMS` (`IDX`),
  CONSTRAINT `FKnr2fb9f4al3pj2jt8rd4kauih` FOREIGN KEY (`USERNAME`) REFERENCES `USERS` (`USERNAME`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `FRIEND` (
  `USERNAME` varchar(255) NOT NULL,
  `FRIEND_USERNAME` varchar(255) NOT NULL,
  `RELATIONS_SHIP_TYPE` enum('BUSINESS','CHILD','FRIEND','PARENT') NOT NULL COMMENT '    [친구타입]\n    PARENT : 멘토\n    CHILD : 멘티\n    FRIEND : 친구\n    BUSINESS : 비지니스\n',
  `ACCEPT_STATUS` bit(1) NOT NULL COMMENT '친구요청 수락 상태 True : 친구, False : 친구 아님',
  `SEND_STATUS` enum('RECEIVE','SEND') NOT NULL COMMENT '친구요청 발신 상태 [발신, 수신]',
  `CREATE_DT` datetime(6) NOT NULL COMMENT '생성일시',
  `UPDATE_DT` datetime(6) NOT NULL COMMENT '수정일시',
  `DELETE_DT` datetime(6) DEFAULT NULL COMMENT '삭제일시',
  `STATUS` CHAR(1) NOT NULL COMMENT '상태',
  PRIMARY KEY (`FRIEND_USERNAME`,`USERNAME`),
  KEY `FKiee50l8ku6of05cmimv7fx09s` (`USERNAME`),
  CONSTRAINT `FKiee50l8ku6of05cmimv7fx09s` FOREIGN KEY (`USERNAME`) REFERENCES `USERS` (`USERNAME`) ON DELETE CASCADE,
  CONSTRAINT `FKnlrrw1qpjhou144c6x8w7ydmf` FOREIGN KEY (`FRIEND_USERNAME`) REFERENCES `USERS` (`USERNAME`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `MAIL` (
  `IDX` bigint NOT NULL AUTO_INCREMENT COMMENT '메일 IDX 번호',
  `EMAIL` varchar(255) NOT NULL COMMENT '이메일',
  `TITLE` varchar(255) NOT NULL COMMENT '메일 제목',
  `CONTENT` longtext NOT NULL COMMENT '메일 내용',
  `CERT_YN` bit(1) DEFAULT NULL COMMENT '인증여부',
  `CERT_NUM` varchar(255) DEFAULT NULL COMMENT '인증번호 [인증메일이 아니면 없을 수 있음]',
  `MAIL_TYPE` enum('GUIDE','REGISTER_CERT','UPDATE_CERT') NOT NULL COMMENT '메일타입 [회원가입 메일, 암호 수정 인증메일 등]',
  `CREATE_DT` datetime(6) NOT NULL COMMENT '생성일시',
  `UPDATE_DT` datetime(6) NOT NULL COMMENT '수정일시',
  PRIMARY KEY (`IDX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `LOGGING` (
  `IDX` int NOT NULL AUTO_INCREMENT COMMENT '로깅 IDX',
  `USERNAME` varchar(500) DEFAULT NULL COMMENT '회원아이디',
  `IP` varchar(25) NOT NULL COMMENT 'IP 주소',
  `TYPE` varchar(20) NOT NULL COMMENT '로깅 타입',
  `MESSAGE` varchar(100) DEFAULT NULL COMMENT '로그 메세지',
  `CREDENTIALS` varchar(500) DEFAULT NULL COMMENT '암호 및 중요정보',
  `CREATE_DT` datetime(6) DEFAULT NULL COMMENT '생성일시',
  PRIMARY KEY (`IDX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `CATEGORY` (
  `IDX` bigint NOT NULL AUTO_INCREMENT COMMENT '카테고리 IDX',
  `USERNAME` varchar(255) NOT NULL COMMENT '작성자',
  `TITLE` varchar(255) NOT NULL COMMENT '카테고리 내용',
  `MAIN_COLOR` varchar(255) NOT NULL COMMENT '카테고리 색상',
  `PUBLIC_STATUS` enum('PARTIAL','PRIVATE','PUBLIC') NOT NULL COMMENT '카테고리 공개여부 [해당 카테고리 Todo 내용을 보일지 말지 결정]',
  `CREATE_DT` datetime(6) NOT NULL COMMENT '생성일시',
  `UPDATE_DT` datetime(6) NOT NULL COMMENT '수정일시',
  `DELETE_DT` datetime(6) DEFAULT NULL COMMENT '삭제일시',
  `STATUS` CHAR(1) NOT NULL COMMENT '상태',
  PRIMARY KEY (`IDX`),
  KEY `FKrthissysx2kh1nv3yphxshc4p` (`USERNAME`),
  CONSTRAINT `FKrthissysx2kh1nv3yphxshc4p` FOREIGN KEY (`USERNAME`) REFERENCES `USERS` (`USERNAME`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `ROUTINE` (
  `IDX` bigint NOT NULL AUTO_INCREMENT COMMENT '루틴 IDX',
  `USERNAME` varchar(255) NOT NULL COMMENT '작성자',
  `CONTENT` varchar(255) DEFAULT NULL COMMENT '루틴 내용',
  `CYCLE_TYPE` enum('EVERY_DAY','EVERY_MONTH','EVERY_WEEK') NOT NULL COMMENT '루틴 반복타입',
  `CYCLE_VALUE` varchar(255) NOT NULL COMMENT '루틴 반복값',
  `RM` varchar(255) DEFAULT NULL COMMENT '비고, 설명',
  `CATEGORY_IDX` bigint DEFAULT NULL COMMENT '카테고리 IDX',
  `START_DT` date NOT NULL COMMENT '루틴 시작일',
  `END_DT` date NOT NULL COMMENT '루틴 종료일',
  `START_TARGET_TM` time(6) DEFAULT NULL COMMENT '루틴의 투두 시작시간',
  `END_TARGET_TM` time(6) DEFAULT NULL COMMENT '루틴의 투두 종료시간',
  `CREATE_DT` datetime(6) NOT NULL COMMENT '생성일시',
  `UPDATE_DT` datetime(6) NOT NULL COMMENT '수정일시',
  `DELETE_DT` datetime(6) DEFAULT NULL COMMENT '삭제일시',
  `STATUS` CHAR(1) NOT NULL COMMENT '상태',
  PRIMARY KEY (`IDX`),
  KEY `FKou3p1e3rfg454fd34jigl6tw3` (`CATEGORY_IDX`),
  KEY `FKbdnl0taunaiiakdkkkt34wvj5` (`USERNAME`),
  CONSTRAINT `FKbdnl0taunaiiakdkkkt34wvj5` FOREIGN KEY (`USERNAME`) REFERENCES `USERS` (`USERNAME`) ON DELETE CASCADE,
  CONSTRAINT `FKou3p1e3rfg454fd34jigl6tw3` FOREIGN KEY (`CATEGORY_IDX`) REFERENCES `CATEGORY` (`IDX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE `TODO` (
  `IDX` bigint NOT NULL AUTO_INCREMENT COMMENT 'IDX 고유값',
  `USERNAME` varchar(255) DEFAULT NULL COMMENT '작성자',
  `CONTENT` varchar(255) NOT NULL COMMENT '투두 내용',
  `TARGET_DATE` date NOT NULL COMMENT '투두 지정일',
  `START_TARGET_TM` time(6) DEFAULT NULL COMMENT '투두 시작시간',
  `END_TARGET_TM` time(6) DEFAULT NULL COMMENT '투두 종료시간',
  `CATEGORY_IDX` bigint DEFAULT NULL COMMENT '카테고리 IDX',
  `ROUTINE_IDX` bigint DEFAULT NULL COMMENT '루틴 IDX',
  `CREATE_DT` datetime(6) NOT NULL COMMENT '생성일시',
  `UPDATE_DT` datetime(6) NOT NULL COMMENT '수정일시',
  `DELETE_DT` datetime(6) DEFAULT NULL COMMENT '삭제일시',
  `STATUS` CHAR(1) NOT NULL COMMENT '상태',
  `PROGRESS_STATUS` smallint COMMENT '진행도',
  PRIMARY KEY (`IDX`),
  KEY `FKou3p1e4wro012h0cpjigl6tw3` (`CATEGORY_IDX`),
  KEY `FKou3p144h83fkd438dfhkl7se3` (`ROUTINE_IDX`),
  KEY `FK6l1up26vvsa5juhluisme9kvy` (`USERNAME`),
  CONSTRAINT `FK6l1up26vvsa5juhluisme9kvy` FOREIGN KEY (`USERNAME`) REFERENCES `USERS` (`USERNAME`) ON DELETE CASCADE,
  CONSTRAINT `FKou3p1e4wro012h0cpjigl6tw3` FOREIGN KEY (`CATEGORY_IDX`) REFERENCES `CATEGORY` (`IDX`),
  CONSTRAINT `FKou3p144h83fkd438dfhkl7se3` FOREIGN KEY (`ROUTINE_IDX`) REFERENCES `ROUTINE` (`IDX`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='TODO 테이블';


CREATE TABLE `TODO_TIMER_HISTORY` (
  `IDX` bigint NOT NULL AUTO_INCREMENT COMMENT '투두 시간 기록 IDX',
  `TODO_IDX` bigint NOT NULL COMMENT '투두 IDX',
  `HISTORY_START_DT` datetime(6) NOT NULL COMMENT '투두 기록 시작 시간',
  `HISTORY_END_DT` datetime(6) NOT NULL COMMENT '투두 기록 종료 시간',
  `TOTAL_TM` time(6) NOT NULL COMMENT '투두 기록 걸린 총 시간',
  PRIMARY KEY (`IDX`),
  KEY `FKeyym8skcbiju6rhwfm0x006rv` (`TODO_IDX`),
  CONSTRAINT `FKeyym8skcbiju6rhwfm0x006rv` FOREIGN KEY (`TODO_IDX`) REFERENCES `TODO` (`IDX`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `D_DAY` (
  `IDX` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK고유키',
  `USERNAME` varchar(255) DEFAULT NULL COMMENT '등록유저',
  `CONTENT` varchar(255) NOT NULL COMMENT 'D_DAY 내용',
  `CREATE_DT` datetime(6) NOT NULL COMMENT '생성일시',
  `TARGET_DEL_YN` bit(1) NOT NULL COMMENT '지정일 이후 삭제여부 [TRUE 일시 배치로 삭제 예정]',
  `TARGET_DT` date NOT NULL COMMENT 'D_DAY 지정일',
  `UPDATE_DT` datetime(6) NOT NULL COMMENT '수정일시',
  `DELETE_DT` datetime(6) DEFAULT NULL COMMENT '삭제일시',
  `STATUS` CHAR(1) NOT NULL COMMENT '상태',
  `COMPLETED` tinyint(1) NOT NULL COMMENT '완료 여부',
  PRIMARY KEY (`IDX`),
  KEY `FKgr3x13xx1tabn4gly396gs0v2` (`USERNAME`),
  CONSTRAINT `FKgr3x13xx1tabn4gly396gs0v2` FOREIGN KEY (`USERNAME`) REFERENCES `USERS` (`USERNAME`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `HOME` (
  `IDX` bigint NOT NULL AUTO_INCREMENT COMMENT 'PK고유키',
  `USERNAME` varchar(255) DEFAULT NULL COMMENT '해당 유저',
  `GOAL` varchar(255) NOT NULL COMMENT '오늘의 목표',
  `MOOD` varchar(255) NOT NULL COMMENT '오늘의 기분',
  `TODAY_DATE` date NOT NULL COMMENT '오늘 날짜',
  PRIMARY KEY (`IDX`),
  KEY `FKgrf34rf43234232396g34rg5` (`USERNAME`),
  CONSTRAINT `FKgrf34rf43234232396g34rg5` FOREIGN KEY (`USERNAME`) REFERENCES `USERS` (`USERNAME`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;