name: CI/CD

on:
  push:
    branches: [ "release" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v3

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
        run: |
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
        shell: bash

      - name: application-dev.yml 파일 만들기
        run: |
          echo "${{ secrets.APPLICATION_DEV_YML }}" > ./src/main/resources/application-dev.yml
        shell: bash

      - name: jwt.yml 파일 만들기
        run: |
          printf "%s" "${{ secrets.JWT_YML }}" > ./src/main/resources/jwt.yml
        shell: bash

      - name: Firebase Service Key 생성
        run: |
          printf "%s" "${{ secrets.FIREBASE_KEY }}" > ./src/main/resources/firebase/timetodo2024-key.json
        shell: bash

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: API 서버 compose 파일 복사
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_SECRET_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "api-compose.yml, ./src/main/resources/timetodo2024-key.json"
          target: "/home/ubuntu/docker/"

      - name: 도커 이미지 빌드 및 푸시
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t harriet99/timetodo-apitest:latest .
          docker push harriet99/timetodo-apitest:latest

      - name: API 서버 배포
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.AWS_SECRET_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # API 컨테이너만 중지하고 제거 -> 새로 배포 -> 사용하지 않는 이미지 정리
          script: |
            cd /home/ubuntu/docker/
            docker stop timetodo-apitest || true
            docker rm timetodo-apitest || true
            docker-compose -f api-compose.yml pull
            docker-compose -f api-compose.yml up -d
            docker image prune -f